version: '3.9'
services:
  api1:
    container_name: api1
    image: coindesk
    ports:
      - "7777:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - coindesk-network
  api2:
    container_name: api2
    image: coindesk
    ports:
      - "6666:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - coindesk-network
  api3:
    container_name: api3
    image: coindesk
    ports:
      - "5555:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
    networks:
      - coindesk-network
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - coindesk-network
networks: 
  coindesk-network:
    driver: bridge